// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql"

	"github.com/google/uuid"
)

type User struct {
	UserID    int32
	Email     string
	FirstName sql.NullString
	LastName  sql.NullString
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type UserCredential struct {
	UserID       int32
	PasswordHash string
}

type UserSession struct {
	SessionID uuid.UUID
	UserID    int32
	Token     string
	CreatedAt sql.NullTime
	ExpiresAt sql.NullTime
}
